#!/bin/sh
# Print the Homebrew cask for a release, using the checksums in SHA256SUMS.txt.
#
#   sh scripts/homebrew-cask.sh 1.2.0 release/SHA256SUMS.txt > Casks/ansible-interactive.rb
set -eu

version="${1:?usage: homebrew-cask.sh <version> <SHA256SUMS.txt>}"
sums="${2:?usage: homebrew-cask.sh <version> <SHA256SUMS.txt>}"
version="${version#v}"

sha() {
	hash="$(awk -v f="ansible-interactive-$1.tar.gz" '$2 == f || $2 == "*" f { print $1 }' "$sums")"
	if [ -z "$hash" ]; then
		echo "No checksum for $1 in $sums" >&2
		exit 1
	fi
	echo "$hash"
}

darwin_arm64="$(sha darwin-arm64)"
darwin_x64="$(sha darwin-x64)"
linux_arm64="$(sha linux-arm64)"
linux_x64="$(sha linux-x64)"

cat <<CASK
# Generated by scripts/homebrew-cask.sh in glhd/ansible-interactive. Do not edit.
cask "ansible-interactive" do
  version "$version"

  on_macos do
    on_arm do
      url "https://github.com/glhd/ansible-interactive/releases/download/v#{version}/ansible-interactive-darwin-arm64.tar.gz"
      sha256 "$darwin_arm64"
    end
    on_intel do
      url "https://github.com/glhd/ansible-interactive/releases/download/v#{version}/ansible-interactive-darwin-x64.tar.gz"
      sha256 "$darwin_x64"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/glhd/ansible-interactive/releases/download/v#{version}/ansible-interactive-linux-arm64.tar.gz"
      sha256 "$linux_arm64"
    end
    on_intel do
      url "https://github.com/glhd/ansible-interactive/releases/download/v#{version}/ansible-interactive-linux-x64.tar.gz"
      sha256 "$linux_x64"
    end
  end

  name "ansible-interactive"
  desc "Interactive prompt for building and running ansible-playbook commands"
  homepage "https://github.com/glhd/ansible-interactive"

  livecheck do
    url :url
    strategy :github_latest
  end

  binary "ansible-interactive"

  # The binary has an ad-hoc signature but isn't notarized, so clear the
  # quarantine flag Homebrew sets on downloads
  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/ansible-interactive"]
    end
  end

  caveats <<~EOS
    ansible-interactive needs Ansible on your PATH, e.g.:
      brew install ansible
    or
      pipx install --include-deps ansible
  EOS
end
CASK
